### ISSUE TITLE
Some events are lost when too many are triggered

### ISSUE THREAD

**Issue by killpowa** [yuanchuan/node-watch#91] opened 2020-03-01 00:47 UTC
This works perfectly with a low amount of events, but if I try to copy 200+ files into the watched directory, some of the files will not trigger the callback. I can consistently reproduce this issue, but every time the number of files that trigger the callback is different. Usually, it's around 150 out of 200.
UPDATE:
It looks like copying files work. Just when I move them it skips some of them. Maybe they're too fast?

**Comment by yuanchuan** [comment] 2020-03-02 09:48
Is there a code sample and a sequence of commands which caused the problem?

**Comment by killpowa** [comment] 2020-03-02 10:00
```
var watch = require('node-watch');

watch('./dir', { recursive: true }, function(evt, name) {
  console.log('%s changed.', name);
});
```

Something like this. Then just start cutting and pasting like 300 files and you should be able to reproduce it.

**Comment by yuanchuan** [comment] 2020-03-02 11:53
OK. I need more information. I can't reproduce it on my computer (Mac, Node v11.7.0, node-watch 0.6.3)

1. How do you test if some of the files do not trigger the callback?
2. Does it happen on cutting or pasting or both?
3. Are there nested directories among the cutting/pasting files?

**Comment by crh3675** [comment] 2020-03-02 23:50
Sounds like a system limit like ulimit or fs.max-open-files issue

**Comment by killpowa** [comment] 2020-03-03 01:12
I test it counting the files that I'm copying, and then implementing a counter in the listener. This just happens on cutting as far as I know. No nested directories. Chokidar and NSFW works perfectly fine

**Comment by yuanchuan** [comment] 2020-03-03 07:13
I wrote a test and nothing went wrong on Travis. Also, I managed to find a Desktop Windows to do 'cutting and pasting' but I couldn't reproduce it either.

There's a delay (200ms) to respond to an event. Maybe there's something wrong about the counting method.

May I know how did you implement the counter?

**Comment by yuanchuan** [comment] 2020-03-03 10:26
Or try both  `node-watch` with option`{ delay: 0 }`   and native `fs.watch()` to see if there's any difference

**Comment by yuanchuan** [comment] 2020-03-09 08:01
Thank you @killpowa for reporting. I'll close it by now.
Also thanks to @crh3675 for the suggestion :)

**Closed by yuanchuan** 2020-03-09 08:01 UTC
